# Generated by Django 4.0.1 on 2022-01-15 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Talaba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=500)),
                ('birth', models.DateField()),
                ('phone', models.IntegerField()),
                ('jinsi', models.CharField(choices=[('Ayol', 'ayol'), ('Erkak', 'erkak')], max_length=300)),
            ],
        ),
    ]
