# Generated by Django 4.0.1 on 2022-01-15 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='talaba',
            name='file',
            field=models.FileField(default=False, upload_to='files'),
        ),
        migrations.AddField(
            model_name='talaba',
            name='image',
            field=models.ImageField(default=False, upload_to='pictures'),
        ),
    ]
